### PR TITLE
fix for closing db in sql worker

### PR DESCRIPTION
**Pull request by WilliamStephens**
Null the db after closing it. This was causing issues when we closed a db and then reopened it because db was never set to null.

### CODE REVIEW

**Comment by dinedal** [comment]
Hi @WilliamStephens first thank you very much for contributing!

I know it can be a bit confusing, but the actual logic for the JS files is written in [CoffeeScript](http://coffeescript.org/), and the worker's logic lives here: https://github.com/kripken/sql.js/blob/master/coffee/worker.coffee

After you make the change to that file, `make worker` will generated the correct `worker.sql.js`

**Comment by WilliamStephens** [comment]
@dinedal Yea no problem! 

After an hour of setup I think I finally got it. When I ran the make file it generated a new sql.js and worker.sql.js and caused a some big diffs that I didn't include. You may want to handle that on your end as I'm not really sure if they are needed or not. I ran the test.sh script and had a bunch of failures but honestly am not sure if I caused those or not. 

First time writing Coffeescript too, so not sure if there is a better way to do this.

**Comment by dinedal** [comment]
Yeah we need the regenerated source as well. Let me see if I can help out later

**Comment by WilliamStephens** [comment]
@dinedal Added the regenerated files

**Pull request closed without merging**
