### PR TITLE
sqlite 3.45.2

### PR DESCRIPTION
**Pull request by lovasoa**

### CODE REVIEW

**Comment by james-bowers** [comment]
Hi @lovasoa - is there any chance this has overwritten the wasm at https://sql.js.org/dist/sql-wasm.wasm ?

**Comment by lovasoa** [comment]
Hi ! Indeed, sql.js has been updated yesterday. The official sql.js.org website always hosts the latest version (since yesterday, 1.10.3, which uses SQLite 3.45.2).

If you depend on sql.js in production, you probably should host it, sql.js.org doesn't make any versioning or availability guarantees.

**Comment by lovasoa** [comment]
And if you found a bug in sql.js, you should report it !

**Comment by james-bowers** [comment]
OK thanks @lovasoa - is it just the one wasm file I need to host? The readme makes it look like there might be multiple with this example:

```
  locateFile: file => `https://sql.js.org/dist/${file}`
```

**Comment by lovasoa** [comment]
In the wasm case, there is only this file. 
If you want something future proof, expose the entire dist folder from the npm package

**Comment by james-bowers** [comment]
> In the wasm case, there is only this file. If you want something future proof, expose the entire dist folder from the npm package

Got it - thanks!

**Pull request merged**
