### PR TITLE
Update api.js to improve documentation

### PR DESCRIPTION
**Pull request by DavidPratten**
To resolve https://github.com/sql-js/sql.js/issues/435

### CODE REVIEW

**Comment by lovasoa** [comment]
Looks good to me, I'll merge as soon as CI passes (looks like you have a formatting issue).

**Comment by DavidPratten** [comment]
I'm getting the hang of it!

**Comment by DavidPratten** [comment]
@lovasoa thanks a good experience.  My first PR!  David

**Comment by lovasoa** [comment]
Thanks for your contribution ! It is live on sql.js.org : https://sql.js.org/documentation/Statement.html

:pray:

**Pull request merged**
