### PR TITLE
Add the 「run」 directive for the webWorker

### PR DESCRIPTION
**Pull request by Airsola**
thx for such helpful project.
just little change.Add the 「run」 directive for the webWorker~

### CODE REVIEW

**Comment by dinedal** [comment]
Looks good, can you re-build and commit the updated files?

**Comment by kaizhu256** [comment]
was the intent of adding `run-command` to allow passing params in webworkers?  if so can we close this as duplicate of #364?

also is `run-command` concurrency-safe? i did try hacking `run-command` into workers in the past, and got weird results when posting multiple-messages concurrently.  it could've been programming error on my part, but i've stuck to `exec` since that experience.

**Comment by lovasoa** [comment]
You can see the commit here. It was not a duplicate of #230 
https://github.com/sql-js/sql.js/pull/209/commits/ed9c56f9281363fd932787358eab0919bbc7e212

I'm not sure exactly what you are referring to by run-command.
When you use a webworker, the messages you send are still handled sequentially on a single thread.  There is no problem with sending a new message before receiving a response for an old one.

**Comment by kaizhu256** [comment]
ok run-directive has different intent and is concurrency-safe.  @airsola, if you still want to contribute, you can submit a new pull-request in vanilla js.

feel free to use commit https://github.com/sql-js/sql.js/pull/364/commits/632effacc63edab1f9905bd036a4a3327be64681 as reference, as the feature-set is somewhat similar, including testcase

**Pull request closed without merging**
